//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackiingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PercentageDone
    {
        public long PercentageDoneID { get; set; }
        public string PercentageDoneName { get; set; }
    }
}
