//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTrackiingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblLogin
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Please Enter Username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        public string Password { get; set; }
        [NotMapped]
        [Compare("Password",ErrorMessage ="Password Doesn't Match.")]
        [Required(ErrorMessage = "Please Enter ConfirmPassword")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please Enter Role")]
        public string Role { get; set; }
    }
}
